# Generated by Django 5.2.3 on 2025-07-21 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_highcosttransportrequest_employee_list_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        migrations.AddField(
            model_name="vehicle",
            name="drivers",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_vehicle", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
