# Generated by Django 5.2.3 on 2025-08-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_vehicle_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="bolo_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="insurance_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
