# Generated by Django 5.2.3 on 2025-07-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_vehicle_driver_vehicle_drivers"),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name="vehicle",
    #         name="driver",
    #     ),
    # ]
