# Generated by Django 5.2.3 on 2025-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_vehicle_bolo_number_vehicle_insurance_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="bolo_number",
            new_name="insurance_date",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="insurance_number",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="bolo_date",
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Marks vehicle as archived (soft deleted)."
            ),
        ),
    ]
