# Generated by Django 5.2.3 on 2025-08-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_rename_bolo_number_vehicle_insurance_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="bolo_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="insurance_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
